f = open("sample.txt",'w+')
f.write("python is awesome\n")
f.writelines(['python\n','django\n','drf\n'])
print('cursor is at', f.tell())
f.seek(0)
print('cursor is at', f.tell())
print(f.read())
f.close()